[build]
  publish = "."
  command = "echo 'Static site ready for deployment'"

[[redirects]]
  from = "/chatbot"
  to = "/chatbot.html"
  status = 200

[[redirects]]
  from = "/report"
  to = "/report.html"
  status = 200

[[redirects]]
  from = "/map"
  to = "/map.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://api.deepseek.com;"
